### ISSUE TITLE
Cannot add a member

### ISSUE THREAD

**Issue by witszymanski** [rolivella/QCloud#2]
Hi!
I cannot add a new lab member. Somehow there is a letter limit which I would exceed by 2 in the Email address of the new member. Is there any workaround? 

![image](https://user-images.githubusercontent.com/15866068/70233525-0a475380-175f-11ea-9294-161a6b2b5392.png)

The ".de" is missing and I cannot type in anything. 

Greets
Witek

**Comment by rolivella** [comment]
Sorry, we missed your issue. We fixed this issue some months ago. Now it should work properly.
