### ISSUE TITLE
Qcloud views show empty

### ISSUE THREAD

**Issue by Arthfael** [rolivella/QCloud#4]
Hi,
I started using QCloud 2 months ago, but when I checked my view recently I am only seeing "No Data Available" in all screens. However, the local client is detecting my files, saying it has uploaded them and moving them to the processed folder, so I would think that it is working properly. I also checked that I am looking at the correct time frame. I have tried opening the website in both Firefox and Chrome. Any help welcome.
Best,

Armel

**Comment by rolivella** [comment]
Hi Armel, could you send me the filenames you cannot see on the website? Thanks.

**Comment by Arthfael** [comment]
Dear Roger,

The file names are:
QCloud_QC01.raw, QCloud_QC01_20201005.raw, QCloud_QC01_20201008.raw, QCloud_QC01_20201021.raw, QCloud_QC01_20201118180416.raw, QCloud_QC01_20201125105538.raw, QCloud_QC01_20201125130743.raw, QCloud_QC02_100ng.raw, QCloud_QC02_100ng_20201118184602.raw, QCloud_QC02_100ng_20201125134924.raw, QCloud_QC02_20201008.raw, QCloud_QC02_20201021.raw, QCloud_QC02_25ng.raw, QCloud_QC02_25ng_20201118202739.raw, QCloud_QC02_25ng_20201125153102.raw
Thank you for your help.
Best regards,

Armel

**Comment by rolivella** [comment]
Just only change "QCloud" for another string and resend the files. For instace, instead of, 

QCloud_QC01.raw

Rename it for: 

test_QC01.raw

And also take into account that you have to send the files from order by acquisition date starting from the older ones. Finally, please send a maximum of 10-15 BSA and 5 HeLa per day. 

Thanks!

**Comment by Arthfael** [comment]
Thanks! I have renamed the files, let's see if this works.
Where can I find this information? I have looked at the tutorials and
gathered that the pattern was QC01 and 2 but why would QCloud in the file
name cause a problem?
Also, what happens if an older file, e.g. one I missed originally, is
uploaded? Is all subsequent information lost?
Best regards,

Armel

**Comment by rolivella** [comment]
It's because the QCrawler parses all the "QC" strings and the first it founds is "QCloud" and it doesn't understand it. 

Unfortunately tou cannot upload older data because of the integrity af the thresholds and guidesets.

**Comment by Arthfael** [comment]
I see. Maybe it would make sense to use a regex like "QC0*[1-3]" to parse
the names?

**Comment by rolivella** [comment]
Yes, I'll consider to add it in later versions, but honestly it's the first time that I encounter this kind of issue.
