### ISSUE TITLE
Security ?

### ISSUE THREAD

**Issue by Kunzol** [rolivella/QCloud#5]
Seems that security is not a high priority.
Passwords are transferred without ssl ...
User input is executed on the server host unparsed ...

I better not add more information to give you the chance to fix things before others do bad things.

**Comment by rolivella** [comment]
We had the change to fix things, indeed. We refactored all code and created a new QCloud version three years ago: https://pubs.acs.org/doi/10.1021/acs.jproteome.0c00853.
